apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-catalog.fullname" . }}-backend
  labels:
    {{- include "product-catalog.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "product-catalog.name" . }}-backend