apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "product-catalog.fullname" . }}-frontend
  labels:
    {{- include "product-catalog.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "product-catalog.name" . }}-frontend
  template:
    metadata:
      labels:
        {{- include "product-catalog.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
