FROM nginx:alpine

RUN apk add --no-cache gettext
RUN rm /etc/nginx/conf.d/default.conf

COPY ./frontend-ui /usr/share/nginx/html
COPY nginx.conf.template /etc/nginx/templates/nginx.conf.template


COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
