replicaCount: 1

backend:
  image:
    repository: <YOUR_BACKEND_ECR_REPO_URL>
    tag: latest
  service:
    port: 80
    targetPort: 8080
  canary:
    enabled: false 
    replicaCount: 1 

frontend:
  image:
    repository: <YOUR_FRONTEND_ECR_REPO_URL>
    tag: latest
  config:
    backendApiUrl: http://backend-api:8222/products
  service:
    port: 80
    targetPort: 80
